print ("I like hockey")
print ("Math")
print ("Baseball")
print ("I like drawing maps")
print ("Video games such as minecraft")
print ("I like travelling")
print ("I like California and the west coast")
print ("I like movies and tv shows")
print ("The Office")